version: 2

project_name: github-issue-cms

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: github-issue-cms
    main: .
    binary: github-issue-cms
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/rokuosan/github-issue-cms/cmd/cli.Version={{ .Version }}

archives:
  - id: default
    ids:
      - github-issue-cms
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  use: github-native

release:
  github:
    owner: rokuosan
    name: github-issue-cms
  prerelease: auto
