github:
  username: 'rokuosan'
  repository: 'github-issue-cms'
  allowed_authors:
    - 'rokuosan'

hugo:
  filename:
    articles: '%Y-%m-%d_%H%M%S.md'
    images: '[:id].png'
  directory:
    articles: 'content/posts'
    images: 'static/images/%Y-%m-%d_%H%M%S'
  url:
    images: '/images/%Y-%m-%d_%H%M%S'

# For page bundle
# hugo:
#   filename:
#     articles: 'index.md'
#     images: '[:id].png'
#   directory:
#     articles: 'content/posts/%Y-%m-%d_%H%M%S'
#     images: 'content/posts/%Y-%m-%d_%H%M%S'
#   url:
#     images: ''
