# [[navbar]]
#     identifier = "setup"
#     name = "導入方法"
#     url = "/ja-jp/setup"
#     weight = 1

# [[navbar]]
#     identifier = "configuration"
#     name = "コンフィグ"
#     url = "/ja-jp/configuration"
#     weight = 2
