baseURL = "https://rokuosan.github.io/github-issue-cms/"
languageCode = "en"
title = "GitHub Issue CMS"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
enableEmoji = true
paginate = 5
enableGitInfo = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
