package subcommand

import (
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"time"

	"github.com/rokuosan/github-issue-cms/pkg/config"
	"github.com/rokuosan/github-issue-cms/pkg/core"
	"github.com/rokuosan/github-issue-cms/pkg/ogimage"
	"github.com/spf13/cobra"
)

// NewOGCImageCommand creates the ogimage subcommand.
func NewOGCImageCommand() *cobra.Command {
	var (
		markdownFile string
		templateFile string
	)

	cmd := &cobra.Command{
		Use:   "ogimage",
		Short: "Generate an OGP image from a local markdown file",
		Long: `Generate an OGP (Open Graph Protocol) image from a local markdown file
that was generated by this tool (Hugo-compatible format with YAML frontmatter).

The generated image is saved as "ogp.jpeg" in the image output directory
configured in gic.config.yaml.

This command requires a headless Chromium browser. By default go-rod
auto-downloads one, or set GIC_CHROMIUM_BIN to point to an existing binary.

Examples:
  # Generate OGP image from a markdown file
  github-issue-cms ogimage -f content/posts/2024-01-15_103000.md

  # Use a custom template
  github-issue-cms ogimage -f article.md -t custom-ogp.html

  # Preview a template while editing it
  github-issue-cms ogimage preview ogp.html`,

		RunE: func(cmd *cobra.Command, args []string) error {
			return runOGCImage(cmd, markdownFile, templateFile)
		},
	}

	cmd.Flags().StringVarP(&markdownFile, "file", "f", "", "Path to the markdown file (required)")
	cmd.Flags().StringVarP(&templateFile, "template", "t", "", "Path to a custom OGP HTML template (optional)")
	_ = cmd.MarkFlagRequired("file")
	cmd.AddCommand(NewOGImagePreviewCommand())

	return cmd
}

func runOGCImage(cmd *cobra.Command, markdownFile, templateFile string) error {
	// Load configuration.
	conf, err := config.Get()
	if err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	// Parse the markdown file into an Article.
	slog.Info("Reading markdown file: " + markdownFile)
	article, err := core.ParseArticleFromMarkdown(markdownFile)
	if err != nil {
		return fmt.Errorf("failed to parse markdown file: %w", err)
	}

	// Convert Article to OGPData.
	data := articleToOGPData(article, conf)

	// Create renderer.
	var renderer *ogimage.Renderer
	if templateFile != "" {
		renderer, err = ogimage.NewRendererWithTemplate(templateFile, "")
	} else {
		renderer, err = ogimage.NewRenderer("")
	}
	if err != nil {
		return fmt.Errorf("failed to create renderer: %w", err)
	}

	// Render the OGP image.
	slog.Info("Generating OGP image...")
	jpeg, err := renderer.Render(cmd.Context(), data)
	if err != nil {
		return fmt.Errorf("failed to render OGP image: %w", err)
	}

	// Determine output path.
	outputPath, err := resolveOGPOutputPath(conf, article)
	if err != nil {
		return fmt.Errorf("failed to resolve output path: %w", err)
	}

	// Ensure output directory exists.
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Write the image.
	if err := os.WriteFile(outputPath, jpeg, 0o644); err != nil {
		return fmt.Errorf("failed to write OGP image: %w", err)
	}

	slog.Info("OGP image generated: " + outputPath)
	return nil
}

// articleToOGPData converts a core.Article to ogimage.OGPData.
// Returns zero-value OGPData if article is nil.
func articleToOGPData(article *core.Article, conf config.Config) ogimage.OGPData {
	if article == nil {
		return ogimage.OGPData{}
	}
	article = article.Clone()
	core.FilterArticleTags(article, conf)
	return ogimage.OGPData{
		Title:    article.Title,
		Author:   article.Author,
		Date:     formatDateForOGP(article.Date),
		Category: article.Category,
		Tags:     article.Tags,
	}
}

// formatDateForOGP formats a date string for display in the OGP image.
func formatDateForOGP(dateStr string) string {
	formats := []string{
		time.RFC3339,
		"2006-01-02T15:04:05Z",
		"2006-01-02",
	}
	for _, layout := range formats {
		if t, err := time.Parse(layout, dateStr); err == nil {
			return t.Format("2006-01-02")
		}
	}
	// If we can't parse it, return as-is.
	return dateStr
}

// resolveOGPOutputPath resolves the output path for the OGP image.
// It uses the image output directory from config and saves as "ogp.jpeg".
func resolveOGPOutputPath(conf config.Config, article *core.Article) (string, error) {
	if article == nil {
		return "", fmt.Errorf("article is nil")
	}
	if conf.Output == nil || conf.Output.Images == nil {
		return "", fmt.Errorf("output images config is not set")
	}

	datetime, err := article.ParseDateTime()
	if err != nil {
		// Fall back to current time if we can't parse the article date.
		datetime = time.Now()
	}

	imageDir := conf.Output.Images.Directory
	if imageDir == "" {
		return "", fmt.Errorf("output images directory is not configured")
	}
	imageDir = config.CompileTimeTemplate(datetime, imageDir)

	return filepath.Clean(filepath.Join(imageDir, "ogp.jpeg")), nil
}
